Clickup task : https://app.clickup.com/t/20d4cwj Description : This PR verifies the connectivity of the rocketchat server and asterisk. This commit verifies that there is a connectivity between rocketchat server and managemenet interface of asterisk. These changes also verify the authentication credentials too. Modifications: 1. Added i get api voipServerConfig.management.checkconnection in app/api/server/v1/voip/server-config.ts This API needs { 	host: String, 	port: String, 	username: String, 	password: String, } 2. Added a new routine to service checkManagementConnection 3. Modified server/services/voip/connector/asterisk/ami/AMIConnection.ts to avoid connection race. Connection happens asynchronously. So we do not get to know immediately if the socket is succesfully connected Hence the server handles the connections in the callbacks instead of creating the connection in the constructor. 4. Necessary wiring around the core connectivity check functionality.
Return values :
In case of success following object is returned
{
	status: 'connected'
}

In case of error following object is returned
{
	status: 'connection-error',
	error: error message describing the reason of the error such as auth failure, connection failure, address does not exist etc.
}