Click the Allow Reacting option error
TypeError: Cannot read property 'set' of undefined
Line 201
Should be "=>" instead of "->"
"@" changed，"@processing" is undefined