[Upstream Catchup] Merge RC:master to develop_pwa (#421)
* Bump version to 3.7.0-develop

* Do not use deprecated express method (#18686)

* Replace assets copy on postinstall with symlinks (#18707)

* Update Meteor to 1.11 (#18754)

* Update Meteor to 1.11

* Update Node version

* Fix livechat view creation

* LingoHub Update :rocket: (#18761)

Manual push by LingoHub User: Diego Sampaio.
Project: Rocket.Chat

Made with :heart: by https://lingohub.com

Co-authored-by: Diego Sampaio <chinello@gmail.com>

* Fix french translations (#18746)

Replace [Nom du site] by [Site_Name]...

* Refactor: Omnichannel Realtime Monitoring (#18666)

Co-authored-by: Guilherme Gazzo <guilherme@gazzo.xyz>

* [FIX] Create Custom OAuth services from environment variables (#17377)

* Fix saveRoomSettings method complexity (#18840)

* [FIX] e.sendToBottomIfNecessaryDebounced is not a function (#18834)

* Log WebDav upload errors (#18849)

* [FIX] File upload (Avatars, Emoji, Sounds) (#18841)

* [FIX] IE11 support livechat widget  (#18850)

* [FIX] Can't change password (#18836)

* [FIX] Admin user blank page (#18851)

* [FIX][ENTERPRISE] Omnichannel service status switching to unavailable (#18835)

* [FIX] User can't invite or join other Omnichannel rooms (#18852)

* [FIX] Omnichannel Current Chats open status filter not working (#18795)

* [FIX] Jitsi call start updating subscriptions (#18837)

* [FIX] Showing alerts during setup wizard (#18862)

* Remember users' 2FA right after registration

* Change register server to false by default

* [FIX] Omnichannel Current Chats open status filter not working (#18795)

* [FIX][ENTERPRISE] Omnichannel service status switching to unavailable (#18835)

* [FIX] File upload (Avatars, Emoji, Sounds) (#18841)

* [FIX] IE11 support livechat widget  (#18850)

* [FIX] Admin user blank page (#18851)

* [FIX] User can't invite or join other Omnichannel rooms (#18852)

* [FIX] Showing alerts during setup wizard (#18862)

* Remember users' 2FA right after registration

* Change register server to false by default

* Bump version to 3.6.1

* LingoHub based on develop (#18828)

* LingoHub Update :rocket:

Manual push by LingoHub User: Diego Sampaio.
Project: Rocket.Chat

Made with :heart: by https://lingohub.com

* LingoHub Update :rocket:

Manual push by LingoHub User: Diego Sampaio.
Project: Rocket.Chat

Made with :heart: by https://lingohub.com

Co-authored-by: Diego Sampaio <chinello@gmail.com>

* [FIX] invite-all-from and invite-all-to commands don't work with multibyte room names (#18919)

* [FIX] If there is `ufs` somewhere in url the request to api always returns 404 (#18874)

* chore(packages): add fixed version of ufs

* test(e2e): test usernames with 'ufs'

* test(ufs-router): remove expect for header

* test: turn test callback synchronous

* test: fix async to use done

* chore(packages/meteor-jalik-ufs): add ufs package

* Revert "test: fix async to use done"

This reverts commit 6276e0bf06060b3d2fca3514b59e4d1acbd5832c.

* Revert "test: turn test callback synchronous"

This reverts commit 2af11bbe555c1cdaae1c925c671b09a6297cfcb6.

* Revert "test(ufs-router): remove expect for header"

This reverts commit 2c4eeb03bec8e0909290db02a9cd2e7fd07ba0a6.

* [FIX] "Save to WebDav" not working (#18883)

* [FIX] Read receipts showing blank names and not marking messages as read (#18918)

* [FIX] Non-upload requests being passed to UFS proxy middleware (#18931)

* fix(ufs-proxy): correct routing pattern

* chore(ufs-proxy): add deprecation console warning

* [FIX] Version update check cron job (#18916)

* [FIX] Ignore User action from user card (#18866)

* [FIX] Custom fields required if minLength set and no text typed (#18838)

* [FIX] Dutch: add translations for missing variables (#18814)

* [FIX] French: Add missing __online__ var (#18813)

* [FIX] Deactivate users that are the last owner of a room using REST API (#18864)

* test: add e2e tests for REST API user deactivation

* fix(app): read confirmRelinquish from HTTP request

* chore(app): remove unnecessary console.log

* [FIX] Show custom fields of invalid type (#18794)

* [FIX] Create Custom OAuth services from environment variables (#17377)

* [FIX] Read receipts showing blank names and not marking messages as read (#18918)

* [FIX] Version update check cron job (#18916)

* [FIX] Ignore User action from user card (#18866)

* [FIX] Deactivate users that are the last owner of a room using REST API (#18864)

* test: add e2e tests for REST API user deactivation

* fix(app): read confirmRelinquish from HTTP request

* chore(app): remove unnecessary console.log

* [FIX] Show custom fields of invalid type (#18794)

* Bump version to 3.6.2

* [FIX] Stop adding push messages to queue if push is disabled (#18830)

* [NEW] "Room avatar changed" system messages (#18839)

* [FIX] PDF not rendering (#18956)

* [FIX] Spurious expert role in startup data (#18667)

* [FIX] Open room after guest registration (#18755)

* [FIX] Block user action (#18950)

* Refactor: Omnichannel Analytics (#18766)

* [FIX] Deactivated users show as offline (#18767)

* [FIX] Reaction buttons not behaving properly (#18832)

* Refactor: Message Audit page & Audit logs (#18808)

* [FIX] "Download my data" popup showing HTML code. (#18947)

* [IMPROVE] Move jump to message outside menu (#18928)

* [FIX] Users not being able to activate/deactivate E2E in DMs (#18943)

* Refactor: Admin permissions page (#18932)

Co-authored-by: Guilherme Gazzo <guilhermegazzo@gmail.com>

* [IMPROVEMENT] Add "Allow_Save_Media_to_Gallery" setting to mobile (#18875)

* Bump lodash.merge from 4.6.1 to 4.6.2 (#18800)

* [FIX] Errors in LDAP avatar sync preventing login (#18948)

* [NEW][Apps] Add support for new livechat guest's and room's events (#18946)

* Add support for new livechat's guest and room events

* Update trigger calls

* Update Apps-Engine version

Co-authored-by: Douglas Gubert <douglas.gubert@gmail.com>

* [NEW][Apps] Add a Livechat API - setCustomFields (#18912)

* Map livechatData to customFields

* Add livechatData field to apps converter

Co-authored-by: Thassio Victor <tvmcarvalho@gmail.com>
Co-authored-by: Douglas Gubert <douglas.gubert@gmail.com>

* [NEW] UploadFS respects $TMPDIR environment variable (#17012)

* [IMPROVE] Stop re-sending push notifications rejected by the gateway (#18608)

Co-authored-by: Diego Sampaio <chinello@gmail.com>

* [FIX] User Info: Email and name/username display (#18976)

* Update Meteor to 1.11.1 (#18959)

* [FIX] API call users.setStatus does not trigger status update of clients (#18961)

* LingoHub Update :rocket: (#18973)

Manual push by LingoHub User: Gabriel Engel.
Project: Rocket.Chat

Made with :heart: by https://lingohub.com

Co-authored-by: Gabriel Engel <gabriel.engel@gmail.com>

* Bump marked from 0.6.3 to 0.7.0 (#18801)

Bumps [marked](https://github.com/markedjs/marked) from 0.6.3 to 0.7.0.
- [Release notes](https://github.com/markedjs/marked/releases)
- [Commits](https://github.com/markedjs/marked/compare/v0.6.3...v0.7.0)

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* Bump Livechat widget (#18977)

* [NEW] Option to require settings on wizard UI via ENV variables (#18974)

Co-authored-by: Martin <martin.schoeler@rocket.chat>

* [NEW] Retention policy precision defined by a cron job expression (#18975)

Co-authored-by: Diego Sampaio <chinello@gmail.com>

* Set some queries to prefer the secondary database (#18887)

* Check i18n file for missing variables (#18762)

* [FIX] Scrollbar mention ticks always rendering as white (#18979)

* [FIX] Purged threads still show as unread (#18944)

Co-authored-by: Diego Sampaio <chinello@gmail.com>
Co-authored-by: Rodrigo Nascimento <rodrigoknascimento@gmail.com>

* [NEW][Apps] Add a new upload API (#18955)

Co-authored-by: Douglas Gubert <douglas.gubert@gmail.com>

* [NEW] Send E2E encrypted messages’ content on push notifications (#18882)

* New: Use database change streams when available (#18892)

Co-authored-by: Diego Sampaio <chinello@gmail.com>

* Bump version to 3.7.0-rc.0

* Regression: Handle MongoDB authentication issues (#18993)

* [FIX] LDAP avatar upload (#18994)

* Bump version to 3.7.0-rc.1

* [FIX] Federation issues (#18978)

* fixed message sending, you should not filter the domains, specially filter by only the local origin/source

* Fixing callback registration

* Increased the rate limiting

* Obbey to settings properties (#19020)

* [FIX] PDF not rendering (#18956)

* [FIX] Errors in LDAP avatar sync preventing login (#18948)

* [FIX] LDAP avatar upload (#18994)

* [FIX] Federation issues (#18978)

* fixed message sending, you should not filter the domains, specially filter by only the local origin/source

* Fixing callback registration

* Increased the rate limiting

* Obbey to settings properties (#19020)

* Bump version to 3.7.0-rc.2

* Bump version to 3.6.3

* Create VIP Sponsors.md

* Regression: Fix login screen reactivity of external login providers (#19033)

* [NEW][Apps] Add support to the "encoding" option in http requests from Apps (#19002)

* Allow specify the encoding of the response data

* Update Apps-Engine version

Co-authored-by: Douglas Gubert <douglas.gubert@gmail.com>
Co-authored-by: Douglas Gubert <d-gubert@users.noreply.github.com>

* Regression: File upload via apps not working in some scenarios (#18995)

* [FIX] [Apps] Fix app user doesn't has permission to upload files

* Fix errorClass [Error]: Forbidden [forbidden]

In `app/file-upload/lib/FileUploadBase.js`, we configured `UploadFS.config.defaultStorePermissions`, which validates `insert(userId, doc)` etc. But the parameter userId cann't be always obtained by this validation method correctly (sometimes it's undefined). Meteor use the Meteor.userId() as its fallback option. So we can wrap the original call with `Meteor.runAsUser` to solve issue.

* Add a new validator into canAccessRoom

canAccessRoom (`app/authorization/server/functions/canAccessRoom.js`) is an essential validator for Rocket.Chat to check whether some user has permissions to access some room. In this PR, we added a new validator that allows app users to access any room on a Rocket.Chat server even if it is not a member of the room.

*  An attempt to fix Meteor code must always run within a Fiber Error

Original Error: "Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment."

* Add support for uploading files by a livecaht visitor

* Support upload files with livechat visitors

* Reduce an unnecessary DB query - Users.findOneById

* Move the "bypass" out of canAccessRoom

Adding a bypass inside canAccessRoom can potentially allow apps to do stuff we're not prepared (yet)

* Update Apps-Engine version

* Some refactoring

* Fix a rateada

Co-authored-by: Douglas Gubert <douglas.gubert@gmail.com>

* [NEW] Apps-Engine v1.18.0 (#19047)

* Regression: Elements select & multiSelect not rendered correctly in the App Settings (#19005)

Co-authored-by: Douglas Gubert <d-gubert@users.noreply.github.com>

* Bump version to 3.7.0-rc.3

* Bump version to 3.7.0-rc.4

* Bump version to 3.7.0

* Update package-lock.json

* Fix import in Omnichannel Filter

* Remove duplicate function

Co-authored-by: Diego Sampaio <chinello@gmail.com>
Co-authored-by: Tasso Evangelista <tasso.evangelista@rocket.chat>
Co-authored-by: Gabriel Engel <gabriel.engel@gmail.com>
Co-authored-by: lsignac <lsignac@users.noreply.github.com>
Co-authored-by: gabriellsh <40830821+gabriellsh@users.noreply.github.com>
Co-authored-by: Guilherme Gazzo <guilherme@gazzo.xyz>
Co-authored-by: Maarten <me@maartendewaard.nl>
Co-authored-by: pierre-lehnen-rc <55164754+pierre-lehnen-rc@users.noreply.github.com>
Co-authored-by: Guilherme Gazzo <guilhermegazzo@gmail.com>
Co-authored-by: Renato Becker <renato.augusto.becker@gmail.com>
Co-authored-by: Felipe Parreira <felipeparreirafb@gmail.com>
Co-authored-by: William Reiske <wreiske@mieweb.com>
Co-authored-by: Karting06 <Karting06@users.noreply.github.com>
Co-authored-by: Gilles Meyer <gilles@gmind.net>
Co-authored-by: Martin Schoeler <martin.schoeler@rocket.chat>
Co-authored-by: Diego Mello <diegolmello@gmail.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Thassio Victor <tvmcarvalho@gmail.com>
Co-authored-by: Douglas Gubert <douglas.gubert@gmail.com>
Co-authored-by: Shiqi Mei <shiqi.mei@rocket.chat>
Co-authored-by: Dustin Skoracki <d-sko@users.noreply.github.com>
Co-authored-by: lingohub[bot] <69908207+lingohub[bot]@users.noreply.github.com>
Co-authored-by: Rodrigo Nascimento <rodrigoknascimento@gmail.com>
Co-authored-by: Alan Sikora <alansikora@gmail.com>
Co-authored-by: Marcelo Schmidt <marcelo.schmidt@rocket.chat>
Co-authored-by: Douglas Gubert <d-gubert@users.noreply.github.com>
Co-authored-by: Shailesh Baldaniya <shaileshbaldaniya351@gmail.com>